### ISSUE TITLE
Modules, functional or OO?

### ISSUE THREAD

**Issue by jacwright** [jacwright/typewriter#4]
Modules are all functional right now.
```js
export default function history(view) {
  // attach listeners, add elements to Paper, do stuff
}
```

In Quill.js they are classes that can have API.

```js
export default class History {
  constructor(view) {
    // attach listeners, add elements to Paper, do stuff
  }

  undo() {}
  redo() {}
}
```

I like the simplicity of the functional modules, but ~I imagine~ APIs will be important. We could do functional APIs like:
```js
export default function history(view) {
  // attach listeners, add elements to Paper, do stuff

  return {
    undo() {},
    redo() {}
  };
}
```

Would that just make it more complex though? Thoughts, alternatives?

**Comment by jacwright** [comment]
I like the mixed approach in theory, but it is impossible to tell if a variable is a regular function or a class constructor in JavaScript. Better to go with one or the other. Still leaning towards functional.

**Comment by jacwright** [comment]
https://github.com/jacwright/typewriter/releases/tag/0.2.3 adds API to modules.

```js
view.modules.history.undo()
```

I think this is the way I want to go.

**Comment by TehShrike** [comment]
http://radar.oreilly.com/2014/03/javascript-without-the-this.html

**Comment by jacwright** [comment]
We will use functions and closures like we have now.

**Comment by seanfcarroll** [comment]
Works for me.
